basePath: /
definitions:
  bean.BlockRo:
    properties:
      hash:
        type: string
      number:
        type: integer
    type: object
  bean.Event:
    additionalProperties: true
    type: object
  bean.EventListRo:
    properties:
      blockRo:
        $ref: '#/definitions/bean.BlockRo'
      cols:
        items:
          type: string
        type: array
      event:
        type: string
      orderRo:
        $ref: '#/definitions/bean.OrderRo'
      pageRo:
        $ref: '#/definitions/bean.PageRo'
      taskId:
        type: integer
      timeRo:
        $ref: '#/definitions/bean.TimeRo'
      txRo:
        $ref: '#/definitions/bean.TxRo'
      wheres:
        items:
          items:
            $ref: '#/definitions/bean.Where'
          type: array
        type: array
    required:
    - event
    - taskId
    type: object
  bean.OrderRo:
    properties:
      feilds:
        items:
          type: string
        type: array
      orderType:
        enum:
        - ASC
        - DESC
        type: string
    type: object
  bean.PageRo:
    properties:
      cursor:
        type: integer
      limit:
        maximum: 100
        minimum: 1
        type: integer
    required:
    - limit
    type: object
  bean.Resp:
    properties:
      resCode:
        type: integer
      resDesc:
        type: string
      result: {}
      traceId:
        type: string
    type: object
  bean.TaskAddRo:
    properties:
      abi:
        type: string
      chainId:
        type: integer
      contract:
        type: string
      interval:
        description: 轮询间隔，建议为区块出块间隔
        type: integer
      rpc:
        type: string
      start:
        type: integer
    required:
    - abi
    - chainId
    - contract
    - interval
    - rpc
    - start
    type: object
  bean.TaskDeleteRo:
    properties:
      id:
        type: integer
    required:
    - id
    type: object
  bean.TaskPauseRo:
    properties:
      id:
        type: integer
      pause:
        type: integer
    required:
    - id
    type: object
  bean.TaskUpdateRo:
    properties:
      abi:
        type: string
      chainId:
        type: integer
      contract:
        type: string
      id:
        type: integer
      interval:
        description: 轮询间隔，建议为区块出块间隔
        type: integer
      rpc:
        type: string
      start:
        type: integer
    required:
    - abi
    - chainId
    - contract
    - id
    - interval
    - rpc
    - start
    type: object
  bean.TimeRo:
    properties:
      begin:
        type: integer
      end:
        type: integer
    type: object
  bean.TxRo:
    properties:
      hash:
        type: string
    type: object
  bean.Where:
    properties:
      name:
        type: string
      op:
        description: can be =、>、<、<> and any operator supported by sql-database
        type: string
      value: {}
    type: object
  model.Task:
    properties:
      abi:
        type: string
      chainId:
        type: integer
      contract:
        type: string
      current:
        type: integer
      deletedAt:
        type: integer
      id:
        type: integer
      interval:
        description: 区块轮询间隔
        type: integer
      paused:
        description: 是否暂停
        type: integer
      rpc:
        type: string
      start:
        type: integer
      updatedAt:
        type: integer
    type: object
info:
  contact: {}
  title: eth-events API
  version: 0.1.0
paths:
  /v1/event/list:
    post:
      consumes:
      - application/json
      description: 查询事件
      parameters:
      - description: request param
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/bean.EventListRo'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            items:
              $ref: '#/definitions/bean.Event'
            type: array
      summary: 查询事件
      tags:
      - Event
  /v1/task/add:
    post:
      consumes:
      - application/json
      description: 添加任务
      parameters:
      - description: request param
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/bean.TaskAddRo'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: integer
      summary: 添加任务
      tags:
      - TASK
  /v1/task/delete:
    post:
      consumes:
      - application/json
      description: 删除任务
      parameters:
      - description: request param
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/bean.TaskDeleteRo'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/bean.Resp'
      summary: 删除任务
      tags:
      - TASK
  /v1/task/list:
    get:
      consumes:
      - application/json
      description: 查询任务列表
      parameters:
      - in: query
        name: cursor
        type: integer
      - in: query
        maximum: 100
        minimum: 1
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            items:
              $ref: '#/definitions/model.Task'
            type: array
      summary: 查询任务列表
      tags:
      - TASK
  /v1/task/pause:
    post:
      consumes:
      - application/json
      description: 任务暂停与运行
      parameters:
      - description: request param
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/bean.TaskPauseRo'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/bean.Resp'
      summary: 任务暂停与运行
      tags:
      - TASK
  /v1/task/update:
    post:
      consumes:
      - application/json
      description: 更新任务
      parameters:
      - description: request param
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/bean.TaskUpdateRo'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/bean.Resp'
      summary: 更新任务
      tags:
      - TASK
swagger: "2.0"
